In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv('df_train_2a.csv')
df_test = pd.read_csv('df_test_2a.csv')

In [133]:
# import os
# data_dir = './Task4_v2'
# activities = ['WALKING', 'WALKING_UPSTAIRS', 'WALKING_DOWNSTAIRS', 'STANDING', 'LAYING', 'SITTING']
# for acivity in activities:
#     print(acivity)
#     files = os.listdir(os.path.join(data_dir, acivity))
#     for file in files:
#         print(file)
#         df = pd.read_csv(os.path.join(data_dir, acivity, file), header=None, skiprows=1)
#         df_downsampled = df.groupby(np.arange(len(df)) // 2).mean()
#         index_50hz = np.linspace(0, len(df_downsampled) - 1, int(len(df_downsampled) * 4/5))
#         df_resampled_50hz = df_downsampled.reindex(index_50hz).interpolate(method='linear')
#         df_resampled_50hz.reset_index(drop=True, inplace=True)
#         df_resampled_50hz.to_csv(file, index=False)

#         start_idx = max(0, (len(df_resampled_50hz) - 500) // 2)
#         end_idx = start_idx + 500
#         df_final = df_resampled_50hz.iloc[start_idx:end_idx]
#         df_final.drop(columns=[0,4], inplace=True)

#         df_final.to_csv("./Tak4_v2_Trimmed"+ '/' + acivity + '/' + 'trimmed_'+ file, index=False, header=False)

In [6]:
df_train

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.848709,0.760164,0.736452,0.748299,0.782848,0.882488,0.958099,0.948714,0.930530,1.003035,...,1.353846,1.326801,1.187265,1.123056,1.044983,0.967130,0.955721,0.940260,0.937370,0.920635
1,0.994932,0.996157,0.997569,0.997141,0.997321,0.995469,0.992603,0.992008,0.996622,1.002989,...,0.996362,1.002647,1.001718,0.996088,0.993776,0.995001,0.995938,0.994459,0.993726,0.994293
2,1.029484,1.027762,1.025952,1.027855,1.029590,1.028772,1.028514,1.025848,1.022338,1.023719,...,1.031729,1.027246,1.023730,1.026660,1.031017,1.030908,1.028934,1.028393,1.028763,1.029616
3,0.873025,0.798615,0.727831,0.681650,0.624199,0.572181,0.627781,0.718508,0.835183,0.959438,...,0.555627,0.549743,0.622078,0.725444,0.821024,0.884565,1.006113,1.119521,1.068676,1.044513
4,0.782344,0.669613,0.622582,0.578245,0.551131,0.594676,0.689110,0.823618,0.891847,0.933120,...,0.581406,0.637681,0.662929,0.757451,0.920345,1.067191,1.129631,1.174664,1.338582,1.426424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,0.772641,0.759789,0.751038,0.879259,0.933638,1.028462,1.194758,1.314722,1.385784,1.293604,...,0.988027,0.980787,1.026476,1.049164,1.129574,1.233709,1.237486,1.244454,1.241550,1.188412
122,1.025773,1.025652,1.025421,1.026544,1.028941,1.028593,1.026072,1.024683,1.024759,1.024907,...,1.024350,1.024815,1.024743,1.025626,1.024969,1.024631,1.027661,1.030127,1.029474,1.027648
123,1.001754,1.005349,1.002868,1.000390,1.001920,0.997394,0.989835,0.983372,0.980548,0.983801,...,0.997297,0.995913,1.005183,1.022058,1.035586,1.039751,1.030010,1.012556,1.005530,1.007701
124,1.561116,1.512604,1.213361,0.817532,0.749051,0.965771,1.081938,1.111484,1.064656,0.918712,...,1.133274,1.158859,1.073613,1.032554,0.985686,0.892834,0.889423,0.865240,0.793612,0.743266


In [7]:
df_test

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,1.315677,1.604243,1.830893,1.898958,1.827327,1.620880,1.316908,1.170661,1.052928,0.754885,...,1.764761,1.639306,1.523885,1.416439,1.240125,1.087496,0.893483,0.738629,0.721044,0.631276
1,1.054856,1.136392,1.156623,1.144792,1.157303,1.256707,1.373923,1.357964,1.260566,1.143371,...,0.922238,0.988027,1.003726,1.025643,1.101458,1.162664,1.131585,1.101898,1.127893,1.159806
2,1.066860,1.057793,1.005084,0.953131,0.936750,0.894240,0.869101,0.777311,0.631513,0.622790,...,1.063830,1.100856,1.181338,1.254771,1.336512,1.414291,1.470916,1.593582,1.656637,1.481759
3,1.036042,1.036788,1.029928,1.022799,1.027641,1.036674,1.035558,1.031314,1.025582,1.022758,...,1.033032,1.029915,1.026137,1.028114,1.028717,1.029478,1.030757,1.028273,1.026989,1.028143
4,1.033301,1.032317,1.032423,1.033606,1.031874,1.029899,1.030803,1.033281,1.034185,1.032604,...,1.035920,1.030554,1.025169,1.030608,1.036265,1.037410,1.038579,1.038102,1.036806,1.033834
5,0.915502,0.954963,0.983694,1.020670,1.046503,1.132012,1.249839,1.310624,1.339386,1.351412,...,1.159150,1.206912,1.251561,1.272171,1.211178,1.108875,1.066814,1.081030,1.146494,1.268024
6,1.291127,1.297432,1.183386,1.182686,1.201565,1.195548,1.192607,1.127848,1.125313,1.278853,...,0.746054,0.790597,0.847483,0.906741,0.906648,0.857204,0.881844,0.903662,0.932606,1.017917
7,1.032340,1.032781,1.033193,1.036511,1.038426,1.027897,1.018963,1.023581,1.033635,1.043224,...,1.030667,1.034737,1.031542,1.023020,1.021244,1.024627,1.025150,1.025423,1.025224,1.024552
8,1.144170,1.248520,1.536808,1.810816,1.961262,1.612221,1.090601,0.832398,0.675541,0.690888,...,0.682072,0.956331,1.097197,1.077151,1.135742,1.157704,1.097518,1.124475,1.249014,1.362685
9,0.906851,0.892674,0.927821,0.876667,0.823696,0.768684,0.729186,0.782357,0.836134,0.904579,...,0.879559,0.846065,0.825003,0.847057,0.868695,0.907191,0.923909,0.939381,0.940602,0.933057


In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [9]:
from MakeDataset import y_train, y_test

Training data shape:  (126, 500, 3)
Testing data shape:  (54, 500, 3)


In [10]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(df_train, y_train)

DecisionTreeClassifier(random_state=42)

In [11]:
y_pred = clf.predict(df_test)

# Calculate accuracy, precision, recall, confusion matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.50
Precision: 0.48
Recall: 0.50
Confusion Matrix:
[[4 3 1 0 0 1]
 [4 2 2 0 1 0]
 [6 2 1 0 0 0]
 [0 0 0 6 2 1]
 [0 0 0 2 7 0]
 [0 0 0 2 0 7]]


In [12]:
# sriv_laying1 = pd.read_csv('Task4/Laying/trimmed_Sriv_1.csv', header=None)

In [13]:
# sriv_laying1.drop(columns=[0,4], inplace=True)

In [14]:
# import os
# activities = ['LAYING', 'SITTING', 'STANDING', 'WALKING', 'WALKING DOWNSTAIRS', 'WALKING UPSTAIRS']
# data_dir = './Task4'
# for activity in activities:
#     print(activity)
#     files = os.listdir(os.path.join(data_dir, activity))
#     for file in files:
#         print(file)
#         df = pd.read_csv(os.path.join(data_dir, activity, file), header=None)
#         df.drop(columns=[0,4], inplace=True)
#         df.to_csv("./Task4"+ '/' + activity + '/' + 'trimmed_'+ file, index=False,header=False)

In [15]:
# import os
# activities = ['LAYING', 'SITTING', 'STANDING', 'WALKING', 'WALKING DOWNSTAIRS', 'WALKING UPSTAIRS']
# data_dir = './Task4'
# for activity in activities:
#     print(activity)
#     files = os.listdir(os.path.join(data_dir, activity))
#     for file in files:
#         print(file)
#         df = pd.read_csv(os.path.join(data_dir, activity, file), header=None)
#         print(df.shape)
#         break

In [16]:
from MakeDataset_Linear import X, y
import pandas as pd

print(X.shape, y.shape)

(36, 500, 3) (36,)


In [17]:
X_train_list = []
X_test_list = []

for i in range(0, 36, 6):
    X_train_list.append(X[i:i + 4, :, :])  # First 4 go to X_train
    X_test_list.append(X[i + 4:i + 6, :, :])  # Next 2 go to X_test

X_train_new = np.concatenate(X_train_list, axis=0)
X_test_new = np.concatenate(X_test_list, axis=0)

print(f'X_train_new shape: {X_train_new.shape}')
print(f'X_test_new shape: {X_test_new.shape}')


X_train_new shape: (24, 500, 3)
X_test_new shape: (12, 500, 3)


In [18]:
y_train_list = []
y_test_list = []

for i in range(0, len(y), 6):
    y_train_list.append(y[i:i + 4])  # First 4 go to y_train
    y_test_list.append(y[i + 4:i + 6])  # Next 2 go to y_test

y_train_new = np.concatenate(y_train_list, axis=0)
y_test_new = np.concatenate(y_test_list, axis=0)

print(f'y_train_new: {y_train_new}')
print(f'y_test_new: {y_test_new}')

y_train_new: [6 6 6 6 4 4 4 4 5 5 5 5 1 1 1 1 3 3 3 3 2 2 2 2]
y_test_new: [6 6 4 4 5 5 1 1 3 3 2 2]


In [19]:
X_norm = np.linalg.norm(X, axis=2)
X_norm.shape

(36, 500)

In [20]:
from MakeDataset import X_train, y_train, X_test, y_test

In [21]:
df_raw_train = pd.read_csv('df_train_2a.csv')

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

clf = DecisionTreeClassifier(random_state=42)
clf.fit(df_raw_train.values, y_train)
y_pred = clf.predict(X_norm)
print("Accuracy for raw data: ", accuracy_score(y_pred, y))

Accuracy for raw data:  0.1388888888888889


In [25]:
import tsfel
import pandas as pd

cfg = tsfel.get_features_by_domain()
tsfel_X = tsfel.time_series_features_extractor(cfg, X)

print(tsfel_X.shape)

/tmp/ipykernel_173429/1426764846.py:5: UserWarning: Using default sampling frequency set in configuration file.
  tsfel_X = tsfel.time_series_features_extractor(cfg, X)


/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES335-Insanity-1/.venv/lib/python3.12/site-packages/tsfel/feature_extraction/features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
/home/sriv/PycharmProjects/ES33

(36, 495)


In [26]:
tsfel_X_train = pd.read_csv('tsfel_x_train.csv')

In [27]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(tsfel_X_train.values, y_train)
y_pred = clf.predict(tsfel_X.values)
print("Accuracy for TSFEL data: ", accuracy_score(y_pred, y))

Accuracy for TSFEL data:  0.2222222222222222


2. Use the data you collected to predict the activities that you performed. Decide whether to apply preprocessing and featurization, and if so, choose the appropriate methods. How did the model perform? [1 marks]

In [28]:
X_train_new.shape

(24, 500, 3)

In [29]:
X_train_new_norm = np.linalg.norm(X_train_new, axis=2)
X_test_new_norm = np.linalg.norm(X_test_new, axis=2)
print(X_train_new_norm.shape, X_test_new_norm.shape)

(24, 500) (12, 500)


In [30]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train_new_norm, y_train_new)
y_pred = clf.predict(X_test_new_norm)
print("Accuracy for our data: ", accuracy_score(y_pred, y_test_new))

Accuracy for our data:  0.5833333333333334
